name: superjson
description: A Dart library providing convenient utilities for safely extracting typed data from JSON structures.
version: 1.0.2
homepage: https://github.com/paschalisp/superjson-dart
topics:
  - json

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  intl: ">=0.17.0 <0.22.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0